/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StlStandaloneSetup extends StlStandaloneSetupGenerated {

	public static void doSetup() {
		new StlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
