/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StlUiModule extends AbstractStlUiModule {

	public StlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
