/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.parser.antlr;

import at.ac.tuwien.big.parser.antlr.internal.InternalStlParser;
import at.ac.tuwien.big.services.StlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class StlParser extends AbstractAntlrParser {

	@Inject
	private StlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStlParser createParser(XtextTokenStream stream) {
		return new InternalStlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}

	public StlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
