/*
 * generated by Xtext 2.12.0
 */
package at.ac.tuwien.big.ide;

import at.ac.tuwien.big.StlRuntimeModule;
import at.ac.tuwien.big.StlStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StlIdeSetup extends StlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StlRuntimeModule(), new StlIdeModule()));
	}
	
}
